dataset: IMAGEFOLDER
train_folder: '/content/drive/MyDrive/Custom_Dataset/training_set'
validation_folder: '/content/drive/MyDrive/Custom_Dataset/validation_set'
test_folder: '/content/drive/MyDrive/Custom_Dataset/testing_set'
num_classes: 10

model: FCMNIST
runtag: face10

QuantType: 4bitsym
NormType: RMS
WScale: PerTensor

network_width1: 64
network_width2: 64
network_width3: 32
#cnn_width: 64

num_epochs: 100
batch_size: 16
learning_rate: 0.0007

scheduler: Cosine
step_size: 20
lr_decay: 0.5
T_0: 10
T_mult: 2

augmentation: true
rotation1: 10
rotation2: 10
elastictransformprobability: 0.0

horizontal_flip: true
horizontal_flip_prob: 0.3

color_jitter: true
brightness: 0.1
contrast: 0.1

random_erasing: true
random_erasing_prob: 0.1
random_erasing_scale_min: 0.02
random_erasing_scale_max: 0.08

lambda_l1: 0.0005
prune_epoch: -1
prune_groupstoprune: 32
prune_totalgroups: 96

maxw_algo: octav
maxw_update_until_epoch: 60
maxw_quantscale: 0.25

mean: 0.4333
std: 0.1472

best_loss_min_delta: 0.01

kfold: true
k_folds: 5
kfold_folder: "/content/drive/MyDrive/Custom_Dataset/Training_set_transformed"

seed: 670
deterministic: true

# Decent seed = 420, 67
# Good run but unstable 670
