dataset: IMAGEFOLDER
#train_folder: '/content/drive/MyDrive/Olivetti_Dataset/olivetti_model_development_ONLY/training_set'
#validation_folder: '/content/drive/MyDrive/Olivetti_Dataset/olivetti_model_development_ONLY/validation_set'
#test_folder: '/content/drive/MyDrive/Olivetti_Dataset/olivetti_FINAL_TEST_SET_LOCKED_ONLY'

train_folder: '/content/drive/MyDrive/Custom_Dataset/trainval_set'
validation_folder: '/content/drive/MyDrive/Custom_Dataset/testing_set/Extended_testing_set'
test_folder: '/content/drive/MyDrive/Custom_Dataset/testing_set/Extended_testing_set'
num_classes: 10

model: CNNMNIST
runtag: face10

QuantType: Binary
NormType: RMS
WScale: PerTensor

network_width1: 96
network_width2: 64
network_width3: 0
cnn_width: 64

num_epochs: 100
batch_size: 8
learning_rate: 0.0005
# can try lower

scheduler: Cosine
step_size: 20
lr_decay: 0.5
T_0: 10
T_mult: 2

augmentation: true
rotation1: 12
rotation2: 12
elastictransformprobability: 0.0

horizontal_flip: false
horizontal_flip_prob: 0.2

color_jitter: true
brightness: 0.3
contrast: 0.3

random_erasing: false
random_erasing_prob: 0.1
random_erasing_scale_min: 0.02
random_erasing_scale_max: 0.08

lambda_l1: 0.0005
prune_epoch: -1
prune_groupstoprune: 32
prune_totalgroups: 96

maxw_algo: octav
maxw_update_until_epoch: 70
maxw_quantscale: 0.25

# mean: 0.1307
# std: 0.3081

mean: 0.005
std: 0.0001

best_loss_min_delta: 0.005

kfold: False
k_folds: 5
kfold_folder: "/content/drive/MyDrive/Custom_Dataset/Pre-processed_Items/Training_set_transformed"

label_smoothing: 0.01
weight_decay: 0.005

seed: 670
deterministic: true

# Decent seed = 420, 67
# Good run but unstable 670
